Book
LifeSourceUA/lifesource.ua pull request #4
Opened 2017-06-11 09:51 UTC by Korovchenko

2017-06-11 21:14 UTC, sergsadovyi requested changes

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Assets/LifeSource/UA.js
> +/* eslint-disable */
Нельзя отключать ESlint

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Assets/LifeSource/RU.js
> +/* eslint-disable */
Нельзя отключать ESlint

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Assets/LifeSource/Arrow.js
> +        color: PropTypes.string
сделать обязательным (везде)

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Assets/LifeSource/Arrow.js
> +        color: ''
удалить

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Book/Authors/Views/Desktop/Styles/desktop.scss
> +    align-items: center;
непонятно...

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Book/Authors/Views/Desktop/Styles/desktopHD.scss
> +    .wrap {
непонятно...

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Book/Authors/Views/Desktop/Styles/desktopMega.scss
> +    .wrap {
непонятно...

2017-06-11 21:14 UTC, sergsadovyi commented on src/components/Book/Authors/Views/Desktop/Styles/desktopWide.scss
> +    .wrap {
непонятно...

2017-06-11 21:14 UTC, Ftornik commented on src/components/Book/Main/Views/Common/Styles/desktop.scss
> +@import 'tabletLandscape';
FIX

2017-06-11 21:14 UTC, Ftornik commented on src/theme/Palette.scss
> +$custom2: rgba(0,0,0,.1);
Этот файл должен быть сгенерирован из Palette.js

2017-06-12 05:27 UTC, Korovchenko commented on src/components/Assets/LifeSource/Arrow.js
> +        color: PropTypes.string
мы же делали дефолтный пропс

2017-06-12 11:36 UTC, sergsadovyi approved these changes

2017-06-12 11:36 UTC, merged